apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "1 2 * * *" # help: https://crontab.guru/#30_15-21_*_*_*
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: guestros/mongodb-backup-s3:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: MONGO_URI
              value: "mongodb://mongo.default.cluster.svc.local:27017"
            - name: S3_BUCKET
              value: "mongodb-backup-bucket"
            - name: S3_ENDPOINT
              value: "https://s3.amazonaws.com"
            # secrets
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3backuptarget
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3backuptarget
                  key: AWS_SECRET_ACCESS_KEY
          restartPolicy: OnFailure