apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-myopia-backup
spec:
  concurrencyPolicy: Forbid
  schedule: "1 2 * * *" # help: https://crontab.guru/#30_15-21_*_*_*
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-myopia-backup
            image: guestros/mongodb-backup-s3:latest
            imagePullPolicy: Always
            env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service.proddb.svc.cluster.local:27017"
            - name: S3_BUCKET
              value: "backup-myopia-prod"
            - name: S3_PATH
              value: "prod/"
            - name: S3_ENDPOINT
              value: "https://s3.amazonaws.com"
            - name: S3_REGION
              value: "eu-central-1"
            # secrets
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3backuptarget
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3backuptarget
                  key: AWS_SECRET_ACCESS_KEY
          restartPolicy: OnFailure